import type {Metadata} from "next";
import "./globals.css";
import {DashboardTemplate} from "@components/layouts/dashboard";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout = ({children}: Readonly<{ children: React.ReactNode; }>) => {
    return (
        <html lang="es">
        <body>
        <DashboardTemplate>
            {children}
        </DashboardTemplate>
        </body>
        </html>
    );
}

export default RootLayout
