version: '3.8'

services:
  dev:
    container_name: dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    environment:
      - APP_ENV=development
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/app/src
      - /app/src/tmp
  rhel:
    container_name: rhel
    build:
      context: .
      dockerfile: Dockerfile
      target: rhel