version: '3.8'

services:
  dev:
    container_name: dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    environment:
      - APP_ENV=development
      - container=docker
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
      - "2345:2345"
    privileged: true
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - .:/app/src
      - /app/src/tmp
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    stop_signal: SIGRTMIN+3
  rhel:
    container_name: rhel
    build:
      context: .
      dockerfile: Dockerfile
      target: rhel