version: '3.8'

services:
  dev:
    container_name: dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/app/src
      - /app/src/tmp
  rhel:
    container_name: rhel
    build:
      context: .
      dockerfile: Dockerfile
      target: rhel