import type {Metadata} from "next";
import {DashboardTemplate} from "@components/layouts/dashboard";
import {fallbackLng, languages} from "@app/i18n/settings";
import {useTranslation} from "@app/i18n";
import {dir} from "i18next";

import "../globals.css";

export async function generateStaticParams() {
    return languages.map((lng) => ({ lng }));
}

export async function generateMetadata({ params: { lng } }: {
    params: {
        lng: string;
    };
}): Promise<Metadata> {
    if (languages.indexOf(lng) < 0) lng = fallbackLng
    // eslint-disable-next-line react-hooks/rules-of-hooks
    const { t } = await useTranslation(lng)
    return {
        title: "Create Next App",
        description: "Generated by create next app",
    }
}

const RootLayout = ({children, params: {lng}}: Readonly<{ children: React.ReactNode; params: {lng: string}}>) => {
    return (
        <html lang={lng} dir={dir(lng)}>
        <body className="bg-base dark:bg-base-dark">
        <DashboardTemplate lng={lng}>
            {children}
        </DashboardTemplate>
        </body>
        </html>
    );
}

export default RootLayout
